services:
  mongo:
    image: mongo
    networks:
      - mongo_network
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./cache:/data/db

  mongo-express:
    image: mongo-express
    networks:
      - mongo_network
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  report:
    build: ./docker/report/
    volumes:
      - ./report:/report
    environment:
      - FILE
    command: >
      asciidoctor-pdf
      -a scripts=cjk
      -a pdf-theme=/report/theme/custom-theme.yml
      -r asciidoctor-diagram
      -a mermaid-puppeteer-config=/puppeteer-config.json
      -n /${FILE}

networks:
  mongo_network:
